### ISSUE TITLE
unable to find corect path

### ISSUE THREAD

**Issue by akhid1000** [tsawler/laravel-filemanager#40]
hy, i just try your package, now i'm little bit confused in where path should i change, my project directory structure like:

Root:
index.php(file index in root, not in public)
.htaccess
-assets(folder for my assets)
--css
--js
-public(my public folder)
--img
-secret(laravel core folder)
--app
--bootstrap
--config(in here lfm.php exist)
--database
--public(new public folder create when i publish lfm, here is vendor folder exist)
---vendor
----laravel-filemanager
-----css
-----files
-----images
-----img
-----js
--resources
--storage
--test
--vendor

it's return an error when i click browse, i believe this is because i'm not doing in corect path
i decide to copy vendor folder in my new public folder into my original public folder, but is not working too
what part should i change to get this works

**Comment by tsawler** [comment]
I think you have a problem with your installation, since much of what you post here is not accurate for a properly installed package. The laravel-filemanager package does not install anything in the root directory of a standard laravel installation; instead, all files are put into place via a standard composer install -- public files go in /laravelroot/public/vendor/tsawler/laravel-filemanager, etc.

It rather looks like you need to remove the files you have, and then follow the installation steps in the readme.
